import 'package:flutter/material.dart';
import '../models/account.dart';
import '../models/budget.dart';
import '../models/category.dart';
import '../models/goal.dart';
import '../models/notification_item.dart';
import '../models/transaction.dart';
import '../models/user_profile.dart';

class SampleData {
  static final UserProfile defaultProfile = UserProfile(
    id: 'user_demo',
    name: 'Alex Morgan',
    email: 'alex.morgan@example.com',
    currency: 'USD',
    primaryGoal: 'Track spending & save money',
    avatarUrl: null,
    notificationsEnabled: true,
  );

  static final List<CategoryModel> defaultCategories = [
    // Expense Categories
    CategoryModel(
      id: 'cat_food',
      name: 'Food & Dining',
      type: CategoryType.expense,
      iconCode: Icons.restaurant.codePoint,
      colorValue: const Color(0xFFF59E0B).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_transport',
      name: 'Transportation',
      type: CategoryType.expense,
      iconCode: Icons.directions_car.codePoint,
      colorValue: const Color(0xFF3B82F6).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_shopping',
      name: 'Shopping',
      type: CategoryType.expense,
      iconCode: Icons.shopping_bag.codePoint,
      colorValue: const Color(0xFFEC4899).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_bills',
      name: 'Bills & Utilities',
      type: CategoryType.expense,
      iconCode: Icons.receipt_long.codePoint,
      colorValue: const Color(0xFFEF4444).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_entertainment',
      name: 'Entertainment',
      type: CategoryType.expense,
      iconCode: Icons.movie.codePoint,
      colorValue: const Color(0xFF8B5CF6).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_health',
      name: 'Health',
      type: CategoryType.expense,
      iconCode: Icons.medical_services.codePoint,
      colorValue: const Color(0xFF10B981).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_education',
      name: 'Education',
      type: CategoryType.expense,
      iconCode: Icons.school.codePoint,
      colorValue: const Color(0xFF0EA5E9).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_travel',
      name: 'Travel',
      type: CategoryType.expense,
      iconCode: Icons.flight.codePoint,
      colorValue: const Color(0xFFF97316).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_subscriptions',
      name: 'Subscriptions',
      type: CategoryType.expense,
      iconCode: Icons.subscriptions.codePoint,
      colorValue: const Color(0xFF6366F1).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_other_exp',
      name: 'Other Expense',
      type: CategoryType.expense,
      iconCode: Icons.more_horiz.codePoint,
      colorValue: const Color(0xFF64748B).value,
      isDefault: true,
    ),

    // Income Categories
    CategoryModel(
      id: 'cat_salary',
      name: 'Salary',
      type: CategoryType.income,
      iconCode: Icons.payments.codePoint,
      colorValue: const Color(0xFF10B981).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_freelance',
      name: 'Freelance',
      type: CategoryType.income,
      iconCode: Icons.laptop_mac.codePoint,
      colorValue: const Color(0xFF14B8A6).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_business',
      name: 'Business',
      type: CategoryType.income,
      iconCode: Icons.store.codePoint,
      colorValue: const Color(0xFF0EA5E9).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_investment',
      name: 'Investment',
      type: CategoryType.income,
      iconCode: Icons.trending_up.codePoint,
      colorValue: const Color(0xFF8B5CF6).value,
      isDefault: true,
    ),
    CategoryModel(
      id: 'cat_gift',
      name: 'Gift',
      type: CategoryType.income,
      iconCode: Icons.card_giftcard.codePoint,
      colorValue: const Color(0xFFF43F5E).value,
      isDefault: true,
    ),
  ];

  static final List<AccountModel> defaultAccounts = [
    AccountModel(
      id: 'acc_checking',
      name: 'Primary Checking (Chase)',
      type: AccountType.bank,
      balance: 8450.50,
      currency: 'USD',
      accountNumberMasked: '•••• 4829',
      iconCode: Icons.account_balance.codePoint,
      colorValue: const Color(0xFF0F172A).value,
      updatedAt: DateTime.now(),
    ),
    AccountModel(
      id: 'acc_savings',
      name: 'High-Yield Savings',
      type: AccountType.savings,
      balance: 15200.00,
      currency: 'USD',
      accountNumberMasked: '•••• 9102',
      iconCode: Icons.savings.codePoint,
      colorValue: const Color(0xFF10B981).value,
      updatedAt: DateTime.now(),
    ),
    AccountModel(
      id: 'acc_credit',
      name: 'Sapphire Credit Card',
      type: AccountType.creditCard,
      balance: -1180.00,
      currency: 'USD',
      accountNumberMasked: '•••• 7731',
      iconCode: Icons.credit_card.codePoint,
      colorValue: const Color(0xFF6366F1).value,
      updatedAt: DateTime.now(),
    ),
    AccountModel(
      id: 'acc_cash',
      name: 'Cash Wallet',
      type: AccountType.cash,
      balance: 320.00,
      currency: 'USD',
      accountNumberMasked: null,
      iconCode: Icons.account_balance_wallet.codePoint,
      colorValue: const Color(0xFFF59E0B).value,
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<BudgetModel> defaultBudgets = [
    BudgetModel(
      id: 'bud_food',
      categoryId: 'cat_food',
      amountLimit: 600.00,
      period: BudgetPeriod.monthly,
      startDate: DateTime(DateTime.now().year, DateTime.now().month, 1),
    ),
    BudgetModel(
      id: 'bud_transport',
      categoryId: 'cat_transport',
      amountLimit: 300.00,
      period: BudgetPeriod.monthly,
      startDate: DateTime(DateTime.now().year, DateTime.now().month, 1),
    ),
    BudgetModel(
      id: 'bud_shopping',
      categoryId: 'cat_shopping',
      amountLimit: 350.00,
      period: BudgetPeriod.monthly,
      startDate: DateTime(DateTime.now().year, DateTime.now().month, 1),
    ),
    BudgetModel(
      id: 'bud_entertainment',
      categoryId: 'cat_entertainment',
      amountLimit: 200.00,
      period: BudgetPeriod.monthly,
      startDate: DateTime(DateTime.now().year, DateTime.now().month, 1),
    ),
  ];

  static final List<GoalModel> defaultGoals = [
    GoalModel(
      id: 'goal_emergency',
      title: 'Emergency Reserve',
      targetAmount: 10000.00,
      currentAmount: 4500.00,
      currency: 'USD',
      targetDate: DateTime.now().add(const Duration(days: 365)),
      iconCode: Icons.shield.codePoint,
      colorValue: const Color(0xFF10B981).value,
      notes: '6 months of living expenses saved in high-yield account.',
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    GoalModel(
      id: 'goal_laptop',
      title: 'New MacBook Pro M3',
      targetAmount: 2500.00,
      currentAmount: 1850.00,
      currency: 'USD',
      targetDate: DateTime.now().add(const Duration(days: 60)),
      iconCode: Icons.laptop.codePoint,
      colorValue: const Color(0xFF0EA5E9).value,
      notes: 'Upgrading work laptop.',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    GoalModel(
      id: 'goal_vacation',
      title: 'Summer Vacation to Japan',
      targetAmount: 4000.00,
      currentAmount: 1200.00,
      currency: 'USD',
      targetDate: DateTime.now().add(const Duration(days: 180)),
      iconCode: Icons.flight_takeoff.codePoint,
      colorValue: const Color(0xFF8B5CF6).value,
      notes: 'Flights and Tokyo hotel fund.',
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
    ),
  ];

  static final List<NotificationItem> defaultNotifications = [
    NotificationItem(
      id: 'notif_1',
      title: 'Budget Warning',
      message: 'You have reached 70% of your Food & Dining budget for this month.',
      date: DateTime.now().subtract(const Duration(hours: 3)),
      isRead: false,
      type: 'budget',
    ),
    NotificationItem(
      id: 'notif_2',
      title: 'Monthly Spending Summary Ready',
      message: 'Your total spending in August was \$2,340.00 across 28 transactions.',
      date: DateTime.now().subtract(const Duration(days: 1)),
      isRead: false,
      type: 'report',
    ),
    NotificationItem(
      id: 'notif_3',
      title: 'Goal Progress Milestone!',
      message: 'You hit 74% of your "New MacBook Pro M3" savings goal. Keep it up!',
      date: DateTime.now().subtract(const Duration(days: 2)),
      isRead: true,
      type: 'goal',
    ),
    NotificationItem(
      id: 'notif_4',
      title: 'Upcoming Subscription',
      message: 'Netflix subscription of \$15.99 is scheduled for tomorrow.',
      date: DateTime.now().subtract(const Duration(days: 3)),
      isRead: true,
      type: 'system',
    ),
  ];

  static List<TransactionModel> getSampleTransactions() {
    final now = DateTime.now();
    return [
      TransactionModel(
        id: 'txn_1',
        userId: 'user_demo',
        type: TransactionType.expense,
        amount: 8.50,
        currency: 'USD',
        categoryId: 'cat_food',
        accountId: 'acc_checking',
        title: 'Starbucks Coffee',
        description: 'Morning espresso and croissant',
        date: DateTime(now.year, now.month, now.day, 10, 42),
        paymentMethod: 'Debit Card',
        notes: 'Team morning coffee',
        receiptUrl: 'receipt_starbucks.jpg',
        createdAt: now,
        updatedAt: now,
      ),
      TransactionModel(
        id: 'txn_2',
        userId: 'user_demo',
        type: TransactionType.expense,
        amount: 24.60,
        currency: 'USD',
        categoryId: 'cat_transport',
        accountId: 'acc_credit',
        title: 'Uber Ride to Downtown',
        description: 'Ride to client presentation',
        date: DateTime(now.year, now.month, now.day, 8, 15),
        paymentMethod: 'Credit Card',
        notes: null,
        receiptUrl: null,
        createdAt: now,
        updatedAt: now,
      ),
      TransactionModel(
        id: 'txn_3',
        userId: 'user_demo',
        type: TransactionType.income,
        amount: 4200.00,
        currency: 'USD',
        categoryId: 'cat_salary',
        accountId: 'acc_checking',
        title: 'TechCorp Salary Deposit',
        description: 'Bi-weekly paycheck',
        date: now.subtract(const Duration(days: 1, hours: 2)),
        paymentMethod: 'Direct Deposit',
        notes: 'Includes quarterly bonus adjustment',
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 1)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      TransactionModel(
        id: 'txn_4',
        userId: 'user_demo',
        type: TransactionType.expense,
        amount: 15.99,
        currency: 'USD',
        categoryId: 'cat_subscriptions',
        accountId: 'acc_credit',
        title: 'Netflix Premium Plan',
        description: 'Monthly streaming subscription',
        date: now.subtract(const Duration(days: 1, hours: 5)),
        paymentMethod: 'Auto Debit',
        notes: null,
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 1)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      TransactionModel(
        id: 'txn_5',
        userId: 'user_demo',
        type: TransactionType.expense,
        amount: 142.80,
        currency: 'USD',
        categoryId: 'cat_food',
        accountId: 'acc_checking',
        title: 'Whole Foods Market',
        description: 'Weekly grocery list',
        date: now.subtract(const Duration(days: 2)),
        paymentMethod: 'Debit Card',
        notes: 'Organic produce and pantry items',
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 2)),
        updatedAt: now.subtract(const Duration(days: 2)),
      ),
      TransactionModel(
        id: 'txn_6',
        userId: 'user_demo',
        type: TransactionType.income,
        amount: 650.00,
        currency: 'USD',
        categoryId: 'cat_freelance',
        accountId: 'acc_checking',
        title: 'Design Consulting Fee',
        description: 'Website UI redesign project',
        date: now.subtract(const Duration(days: 3)),
        paymentMethod: 'Bank Wire',
        notes: 'Final invoice payout',
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 3)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      TransactionModel(
        id: 'txn_7',
        userId: 'user_demo',
        type: TransactionType.expense,
        amount: 85.00,
        currency: 'USD',
        categoryId: 'cat_bills',
        accountId: 'acc_checking',
        title: 'Electricity & Gas Utility',
        description: 'Monthly power bill',
        date: now.subtract(const Duration(days: 4)),
        paymentMethod: 'Online Banking',
        notes: null,
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 4)),
        updatedAt: now.subtract(const Duration(days: 4)),
      ),
      TransactionModel(
        id: 'txn_8',
        userId: 'user_demo',
        type: TransactionType.expense,
        amount: 112.50,
        currency: 'USD',
        categoryId: 'cat_shopping',
        accountId: 'acc_credit',
        title: 'Nike Store',
        description: 'Running shoes',
        date: now.subtract(const Duration(days: 5)),
        paymentMethod: 'Credit Card',
        notes: 'On sale 20% off',
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 5)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      TransactionModel(
        id: 'txn_9',
        userId: 'user_demo',
        type: TransactionType.expense,
        amount: 45.00,
        currency: 'USD',
        categoryId: 'cat_entertainment',
        accountId: 'acc_cash',
        title: 'AMC Movie Theater & Snacks',
        description: 'Weekend movie tickets',
        date: now.subtract(const Duration(days: 6)),
        paymentMethod: 'Cash',
        notes: null,
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 6)),
        updatedAt: now.subtract(const Duration(days: 6)),
      ),
      TransactionModel(
        id: 'txn_10',
        userId: 'user_demo',
        type: TransactionType.transfer,
        amount: 500.00,
        currency: 'USD',
        categoryId: 'cat_other_exp',
        accountId: 'acc_checking',
        toAccountId: 'acc_savings',
        title: 'Savings Transfer',
        description: 'Monthly savings auto-deposit',
        date: now.subtract(const Duration(days: 7)),
        paymentMethod: 'Internal Transfer',
        notes: 'Added to Emergency Fund',
        receiptUrl: null,
        createdAt: now.subtract(const Duration(days: 7)),
        updatedAt: now.subtract(const Duration(days: 7)),
      ),
    ];
  }
}
